//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MuseumModel", "FK_tblOrderForms_tblBuyers", "tblBuyers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WcfServiceMuseumNew.tblBuyer), "tblOrderForms", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfServiceMuseumNew.tblOrderForm), true)]
[assembly: EdmRelationshipAttribute("MuseumModel", "FK_tblExhibits_tblLocations", "tblLocations", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WcfServiceMuseumNew.tblLocation), "tblExhibits", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfServiceMuseumNew.tblExhibit), true)]
[assembly: EdmRelationshipAttribute("MuseumModel", "FK_tblExhibits_tblOrderForms", "tblOrderForms", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WcfServiceMuseumNew.tblOrderForm), "tblExhibits", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfServiceMuseumNew.tblExhibit), true)]
[assembly: EdmRelationshipAttribute("MuseumModel", "FK_tblLocations_tblMuseum", "tblMuseum", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WcfServiceMuseumNew.tblMuseum), "tblLocations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfServiceMuseumNew.tblLocation), true)]

#endregion

namespace WcfServiceMuseumNew
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MuseumEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MuseumEntities object using the connection string found in the 'MuseumEntities' section of the application configuration file.
        /// </summary>
        public MuseumEntities() : base("name=MuseumEntities", "MuseumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MuseumEntities object.
        /// </summary>
        public MuseumEntities(string connectionString) : base(connectionString, "MuseumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MuseumEntities object.
        /// </summary>
        public MuseumEntities(EntityConnection connection) : base(connection, "MuseumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblBuyer> tblBuyers
        {
            get
            {
                if ((_tblBuyers == null))
                {
                    _tblBuyers = base.CreateObjectSet<tblBuyer>("tblBuyers");
                }
                return _tblBuyers;
            }
        }
        private ObjectSet<tblBuyer> _tblBuyers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblExhibit> tblExhibits
        {
            get
            {
                if ((_tblExhibits == null))
                {
                    _tblExhibits = base.CreateObjectSet<tblExhibit>("tblExhibits");
                }
                return _tblExhibits;
            }
        }
        private ObjectSet<tblExhibit> _tblExhibits;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblLocation> tblLocations
        {
            get
            {
                if ((_tblLocations == null))
                {
                    _tblLocations = base.CreateObjectSet<tblLocation>("tblLocations");
                }
                return _tblLocations;
            }
        }
        private ObjectSet<tblLocation> _tblLocations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMuseum> tblMuseums
        {
            get
            {
                if ((_tblMuseums == null))
                {
                    _tblMuseums = base.CreateObjectSet<tblMuseum>("tblMuseums");
                }
                return _tblMuseums;
            }
        }
        private ObjectSet<tblMuseum> _tblMuseums;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblOrderForm> tblOrderForms
        {
            get
            {
                if ((_tblOrderForms == null))
                {
                    _tblOrderForms = base.CreateObjectSet<tblOrderForm>("tblOrderForms");
                }
                return _tblOrderForms;
            }
        }
        private ObjectSet<tblOrderForm> _tblOrderForms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUser> tblUsers
        {
            get
            {
                if ((_tblUsers == null))
                {
                    _tblUsers = base.CreateObjectSet<tblUser>("tblUsers");
                }
                return _tblUsers;
            }
        }
        private ObjectSet<tblUser> _tblUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MuseumView> MuseumViews
        {
            get
            {
                if ((_MuseumViews == null))
                {
                    _MuseumViews = base.CreateObjectSet<MuseumView>("MuseumViews");
                }
                return _MuseumViews;
            }
        }
        private ObjectSet<MuseumView> _MuseumViews;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblBuyers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblBuyers(tblBuyer tblBuyer)
        {
            base.AddObject("tblBuyers", tblBuyer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblExhibits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblExhibits(tblExhibit tblExhibit)
        {
            base.AddObject("tblExhibits", tblExhibit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblLocations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblLocations(tblLocation tblLocation)
        {
            base.AddObject("tblLocations", tblLocation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMuseums EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMuseums(tblMuseum tblMuseum)
        {
            base.AddObject("tblMuseums", tblMuseum);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblOrderForms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblOrderForms(tblOrderForm tblOrderForm)
        {
            base.AddObject("tblOrderForms", tblOrderForm);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUsers(tblUser tblUser)
        {
            base.AddObject("tblUsers", tblUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MuseumViews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMuseumViews(MuseumView museumView)
        {
            base.AddObject("MuseumViews", museumView);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MuseumModel", Name="MuseumView")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MuseumView : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MuseumView object.
        /// </summary>
        /// <param name="locationId">Initial value of the LocationId property.</param>
        /// <param name="locationName">Initial value of the LocationName property.</param>
        /// <param name="exhibitId">Initial value of the ExhibitId property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="locationIdFK">Initial value of the LocationIdFK property.</param>
        /// <param name="orderFormIdFK">Initial value of the OrderFormIdFK property.</param>
        /// <param name="buyerId">Initial value of the BuyerId property.</param>
        /// <param name="buyersName">Initial value of the BuyersName property.</param>
        /// <param name="buyersSurname">Initial value of the BuyersSurname property.</param>
        /// <param name="buyersAddress">Initial value of the BuyersAddress property.</param>
        /// <param name="museumId">Initial value of the MuseumId property.</param>
        /// <param name="museumName">Initial value of the MuseumName property.</param>
        /// <param name="orderFormId">Initial value of the OrderFormId property.</param>
        /// <param name="buyerIdFk">Initial value of the BuyerIdFk property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="isAdministrator">Initial value of the IsAdministrator property.</param>
        public static MuseumView CreateMuseumView(global::System.Int32 locationId, global::System.String locationName, global::System.Int32 exhibitId, global::System.String type, global::System.Int32 locationIdFK, global::System.Int32 orderFormIdFK, global::System.Int32 buyerId, global::System.String buyersName, global::System.String buyersSurname, global::System.String buyersAddress, global::System.Int32 museumId, global::System.String museumName, global::System.Int32 orderFormId, global::System.Int32 buyerIdFk, global::System.Int32 userId, global::System.String name, global::System.String userName, global::System.String password, global::System.Boolean isAdministrator)
        {
            MuseumView museumView = new MuseumView();
            museumView.LocationId = locationId;
            museumView.LocationName = locationName;
            museumView.ExhibitId = exhibitId;
            museumView.Type = type;
            museumView.LocationIdFK = locationIdFK;
            museumView.OrderFormIdFK = orderFormIdFK;
            museumView.BuyerId = buyerId;
            museumView.BuyersName = buyersName;
            museumView.BuyersSurname = buyersSurname;
            museumView.BuyersAddress = buyersAddress;
            museumView.MuseumId = museumId;
            museumView.MuseumName = museumName;
            museumView.OrderFormId = orderFormId;
            museumView.BuyerIdFk = buyerIdFk;
            museumView.UserId = userId;
            museumView.Name = name;
            museumView.UserName = userName;
            museumView.Password = password;
            museumView.IsAdministrator = isAdministrator;
            return museumView;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationId
        {
            get
            {
                return _LocationId;
            }
            set
            {
                if (_LocationId != value)
                {
                    OnLocationIdChanging(value);
                    ReportPropertyChanging("LocationId");
                    _LocationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocationId");
                    OnLocationIdChanged();
                }
            }
        }
        private global::System.Int32 _LocationId;
        partial void OnLocationIdChanging(global::System.Int32 value);
        partial void OnLocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LocationName
        {
            get
            {
                return _LocationName;
            }
            set
            {
                if (_LocationName != value)
                {
                    OnLocationNameChanging(value);
                    ReportPropertyChanging("LocationName");
                    _LocationName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("LocationName");
                    OnLocationNameChanged();
                }
            }
        }
        private global::System.String _LocationName;
        partial void OnLocationNameChanging(global::System.String value);
        partial void OnLocationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surface_m2_
        {
            get
            {
                return _Surface_m2_;
            }
            set
            {
                OnSurface_m2_Changing(value);
                ReportPropertyChanging("Surface_m2_");
                _Surface_m2_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surface_m2_");
                OnSurface_m2_Changed();
            }
        }
        private global::System.String _Surface_m2_;
        partial void OnSurface_m2_Changing(global::System.String value);
        partial void OnSurface_m2_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LeasePrice
        {
            get
            {
                return _LeasePrice;
            }
            set
            {
                OnLeasePriceChanging(value);
                ReportPropertyChanging("LeasePrice");
                _LeasePrice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LeasePrice");
                OnLeasePriceChanged();
            }
        }
        private global::System.String _LeasePrice;
        partial void OnLeasePriceChanging(global::System.String value);
        partial void OnLeasePriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MuseumIdFK
        {
            get
            {
                return _MuseumIdFK;
            }
            set
            {
                OnMuseumIdFKChanging(value);
                ReportPropertyChanging("MuseumIdFK");
                _MuseumIdFK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MuseumIdFK");
                OnMuseumIdFKChanged();
            }
        }
        private Nullable<global::System.Int32> _MuseumIdFK;
        partial void OnMuseumIdFKChanging(Nullable<global::System.Int32> value);
        partial void OnMuseumIdFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExhibitId
        {
            get
            {
                return _ExhibitId;
            }
            set
            {
                if (_ExhibitId != value)
                {
                    OnExhibitIdChanging(value);
                    ReportPropertyChanging("ExhibitId");
                    _ExhibitId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ExhibitId");
                    OnExhibitIdChanged();
                }
            }
        }
        private global::System.Int32 _ExhibitId;
        partial void OnExhibitIdChanging(global::System.Int32 value);
        partial void OnExhibitIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                if (_Type != value)
                {
                    OnTypeChanging(value);
                    ReportPropertyChanging("Type");
                    _Type = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Type");
                    OnTypeChanged();
                }
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dimensions
        {
            get
            {
                return _Dimensions;
            }
            set
            {
                OnDimensionsChanging(value);
                ReportPropertyChanging("Dimensions");
                _Dimensions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dimensions");
                OnDimensionsChanged();
            }
        }
        private global::System.String _Dimensions;
        partial void OnDimensionsChanging(global::System.String value);
        partial void OnDimensionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HistoricPeriod
        {
            get
            {
                return _HistoricPeriod;
            }
            set
            {
                OnHistoricPeriodChanging(value);
                ReportPropertyChanging("HistoricPeriod");
                _HistoricPeriod = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HistoricPeriod");
                OnHistoricPeriodChanged();
            }
        }
        private global::System.String _HistoricPeriod;
        partial void OnHistoricPeriodChanging(global::System.String value);
        partial void OnHistoricPeriodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationIdFK
        {
            get
            {
                return _LocationIdFK;
            }
            set
            {
                if (_LocationIdFK != value)
                {
                    OnLocationIdFKChanging(value);
                    ReportPropertyChanging("LocationIdFK");
                    _LocationIdFK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocationIdFK");
                    OnLocationIdFKChanged();
                }
            }
        }
        private global::System.Int32 _LocationIdFK;
        partial void OnLocationIdFKChanging(global::System.Int32 value);
        partial void OnLocationIdFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderFormIdFK
        {
            get
            {
                return _OrderFormIdFK;
            }
            set
            {
                if (_OrderFormIdFK != value)
                {
                    OnOrderFormIdFKChanging(value);
                    ReportPropertyChanging("OrderFormIdFK");
                    _OrderFormIdFK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderFormIdFK");
                    OnOrderFormIdFKChanged();
                }
            }
        }
        private global::System.Int32 _OrderFormIdFK;
        partial void OnOrderFormIdFKChanging(global::System.Int32 value);
        partial void OnOrderFormIdFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuyerId
        {
            get
            {
                return _BuyerId;
            }
            set
            {
                if (_BuyerId != value)
                {
                    OnBuyerIdChanging(value);
                    ReportPropertyChanging("BuyerId");
                    _BuyerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BuyerId");
                    OnBuyerIdChanged();
                }
            }
        }
        private global::System.Int32 _BuyerId;
        partial void OnBuyerIdChanging(global::System.Int32 value);
        partial void OnBuyerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BuyersName
        {
            get
            {
                return _BuyersName;
            }
            set
            {
                if (_BuyersName != value)
                {
                    OnBuyersNameChanging(value);
                    ReportPropertyChanging("BuyersName");
                    _BuyersName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BuyersName");
                    OnBuyersNameChanged();
                }
            }
        }
        private global::System.String _BuyersName;
        partial void OnBuyersNameChanging(global::System.String value);
        partial void OnBuyersNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BuyersSurname
        {
            get
            {
                return _BuyersSurname;
            }
            set
            {
                if (_BuyersSurname != value)
                {
                    OnBuyersSurnameChanging(value);
                    ReportPropertyChanging("BuyersSurname");
                    _BuyersSurname = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BuyersSurname");
                    OnBuyersSurnameChanged();
                }
            }
        }
        private global::System.String _BuyersSurname;
        partial void OnBuyersSurnameChanging(global::System.String value);
        partial void OnBuyersSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BuyersAddress
        {
            get
            {
                return _BuyersAddress;
            }
            set
            {
                if (_BuyersAddress != value)
                {
                    OnBuyersAddressChanging(value);
                    ReportPropertyChanging("BuyersAddress");
                    _BuyersAddress = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BuyersAddress");
                    OnBuyersAddressChanged();
                }
            }
        }
        private global::System.String _BuyersAddress;
        partial void OnBuyersAddressChanging(global::System.String value);
        partial void OnBuyersAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BuyersCountry
        {
            get
            {
                return _BuyersCountry;
            }
            set
            {
                OnBuyersCountryChanging(value);
                ReportPropertyChanging("BuyersCountry");
                _BuyersCountry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BuyersCountry");
                OnBuyersCountryChanged();
            }
        }
        private global::System.String _BuyersCountry;
        partial void OnBuyersCountryChanging(global::System.String value);
        partial void OnBuyersCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MuseumId
        {
            get
            {
                return _MuseumId;
            }
            set
            {
                if (_MuseumId != value)
                {
                    OnMuseumIdChanging(value);
                    ReportPropertyChanging("MuseumId");
                    _MuseumId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MuseumId");
                    OnMuseumIdChanged();
                }
            }
        }
        private global::System.Int32 _MuseumId;
        partial void OnMuseumIdChanging(global::System.Int32 value);
        partial void OnMuseumIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MuseumName
        {
            get
            {
                return _MuseumName;
            }
            set
            {
                if (_MuseumName != value)
                {
                    OnMuseumNameChanging(value);
                    ReportPropertyChanging("MuseumName");
                    _MuseumName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MuseumName");
                    OnMuseumNameChanged();
                }
            }
        }
        private global::System.String _MuseumName;
        partial void OnMuseumNameChanging(global::System.String value);
        partial void OnMuseumNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MuseumAddress
        {
            get
            {
                return _MuseumAddress;
            }
            set
            {
                OnMuseumAddressChanging(value);
                ReportPropertyChanging("MuseumAddress");
                _MuseumAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MuseumAddress");
                OnMuseumAddressChanged();
            }
        }
        private global::System.String _MuseumAddress;
        partial void OnMuseumAddressChanging(global::System.String value);
        partial void OnMuseumAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Established
        {
            get
            {
                return _Established;
            }
            set
            {
                OnEstablishedChanging(value);
                ReportPropertyChanging("Established");
                _Established = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Established");
                OnEstablishedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Established;
        partial void OnEstablishedChanging(Nullable<global::System.DateTime> value);
        partial void OnEstablishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderFormId
        {
            get
            {
                return _OrderFormId;
            }
            set
            {
                if (_OrderFormId != value)
                {
                    OnOrderFormIdChanging(value);
                    ReportPropertyChanging("OrderFormId");
                    _OrderFormId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderFormId");
                    OnOrderFormIdChanged();
                }
            }
        }
        private global::System.Int32 _OrderFormId;
        partial void OnOrderFormIdChanging(global::System.Int32 value);
        partial void OnOrderFormIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BuyerAdress
        {
            get
            {
                return _BuyerAdress;
            }
            set
            {
                OnBuyerAdressChanging(value);
                ReportPropertyChanging("BuyerAdress");
                _BuyerAdress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BuyerAdress");
                OnBuyerAdressChanged();
            }
        }
        private global::System.String _BuyerAdress;
        partial void OnBuyerAdressChanging(global::System.String value);
        partial void OnBuyerAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuyerIdFk
        {
            get
            {
                return _BuyerIdFk;
            }
            set
            {
                if (_BuyerIdFk != value)
                {
                    OnBuyerIdFkChanging(value);
                    ReportPropertyChanging("BuyerIdFk");
                    _BuyerIdFk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BuyerIdFk");
                    OnBuyerIdFkChanged();
                }
            }
        }
        private global::System.Int32 _BuyerIdFk;
        partial void OnBuyerIdFkChanging(global::System.Int32 value);
        partial void OnBuyerIdFkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                if (_Password != value)
                {
                    OnPasswordChanging(value);
                    ReportPropertyChanging("Password");
                    _Password = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Password");
                    OnPasswordChanged();
                }
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdministrator
        {
            get
            {
                return _IsAdministrator;
            }
            set
            {
                if (_IsAdministrator != value)
                {
                    OnIsAdministratorChanging(value);
                    ReportPropertyChanging("IsAdministrator");
                    _IsAdministrator = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IsAdministrator");
                    OnIsAdministratorChanged();
                }
            }
        }
        private global::System.Boolean _IsAdministrator;
        partial void OnIsAdministratorChanging(global::System.Boolean value);
        partial void OnIsAdministratorChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MuseumModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MuseumModel", Name="tblBuyer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblBuyer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblBuyer object.
        /// </summary>
        /// <param name="buyerId">Initial value of the BuyerId property.</param>
        /// <param name="buyersName">Initial value of the BuyersName property.</param>
        /// <param name="buyersSurname">Initial value of the BuyersSurname property.</param>
        /// <param name="buyersAddress">Initial value of the BuyersAddress property.</param>
        public static tblBuyer CreatetblBuyer(global::System.Int32 buyerId, global::System.String buyersName, global::System.String buyersSurname, global::System.String buyersAddress)
        {
            tblBuyer tblBuyer = new tblBuyer();
            tblBuyer.BuyerId = buyerId;
            tblBuyer.BuyersName = buyersName;
            tblBuyer.BuyersSurname = buyersSurname;
            tblBuyer.BuyersAddress = buyersAddress;
            return tblBuyer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuyerId
        {
            get
            {
                return _BuyerId;
            }
            set
            {
                if (_BuyerId != value)
                {
                    OnBuyerIdChanging(value);
                    ReportPropertyChanging("BuyerId");
                    _BuyerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BuyerId");
                    OnBuyerIdChanged();
                }
            }
        }
        private global::System.Int32 _BuyerId;
        partial void OnBuyerIdChanging(global::System.Int32 value);
        partial void OnBuyerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BuyersName
        {
            get
            {
                return _BuyersName;
            }
            set
            {
                OnBuyersNameChanging(value);
                ReportPropertyChanging("BuyersName");
                _BuyersName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BuyersName");
                OnBuyersNameChanged();
            }
        }
        private global::System.String _BuyersName;
        partial void OnBuyersNameChanging(global::System.String value);
        partial void OnBuyersNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BuyersSurname
        {
            get
            {
                return _BuyersSurname;
            }
            set
            {
                OnBuyersSurnameChanging(value);
                ReportPropertyChanging("BuyersSurname");
                _BuyersSurname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BuyersSurname");
                OnBuyersSurnameChanged();
            }
        }
        private global::System.String _BuyersSurname;
        partial void OnBuyersSurnameChanging(global::System.String value);
        partial void OnBuyersSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BuyersAddress
        {
            get
            {
                return _BuyersAddress;
            }
            set
            {
                OnBuyersAddressChanging(value);
                ReportPropertyChanging("BuyersAddress");
                _BuyersAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BuyersAddress");
                OnBuyersAddressChanged();
            }
        }
        private global::System.String _BuyersAddress;
        partial void OnBuyersAddressChanging(global::System.String value);
        partial void OnBuyersAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BuyersCountry
        {
            get
            {
                return _BuyersCountry;
            }
            set
            {
                OnBuyersCountryChanging(value);
                ReportPropertyChanging("BuyersCountry");
                _BuyersCountry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BuyersCountry");
                OnBuyersCountryChanged();
            }
        }
        private global::System.String _BuyersCountry;
        partial void OnBuyersCountryChanging(global::System.String value);
        partial void OnBuyersCountryChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MuseumModel", "FK_tblOrderForms_tblBuyers", "tblOrderForms")]
        public EntityCollection<tblOrderForm> tblOrderForms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblOrderForm>("MuseumModel.FK_tblOrderForms_tblBuyers", "tblOrderForms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblOrderForm>("MuseumModel.FK_tblOrderForms_tblBuyers", "tblOrderForms", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MuseumModel", Name="tblExhibit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblExhibit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblExhibit object.
        /// </summary>
        /// <param name="exhibitId">Initial value of the ExhibitId property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="locationIdFK">Initial value of the LocationIdFK property.</param>
        /// <param name="orderFormIdFK">Initial value of the OrderFormIdFK property.</param>
        public static tblExhibit CreatetblExhibit(global::System.Int32 exhibitId, global::System.String type, global::System.Int32 locationIdFK, global::System.Int32 orderFormIdFK)
        {
            tblExhibit tblExhibit = new tblExhibit();
            tblExhibit.ExhibitId = exhibitId;
            tblExhibit.Type = type;
            tblExhibit.LocationIdFK = locationIdFK;
            tblExhibit.OrderFormIdFK = orderFormIdFK;
            return tblExhibit;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExhibitId
        {
            get
            {
                return _ExhibitId;
            }
            set
            {
                if (_ExhibitId != value)
                {
                    OnExhibitIdChanging(value);
                    ReportPropertyChanging("ExhibitId");
                    _ExhibitId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ExhibitId");
                    OnExhibitIdChanged();
                }
            }
        }
        private global::System.Int32 _ExhibitId;
        partial void OnExhibitIdChanging(global::System.Int32 value);
        partial void OnExhibitIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dimensions
        {
            get
            {
                return _Dimensions;
            }
            set
            {
                OnDimensionsChanging(value);
                ReportPropertyChanging("Dimensions");
                _Dimensions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dimensions");
                OnDimensionsChanged();
            }
        }
        private global::System.String _Dimensions;
        partial void OnDimensionsChanging(global::System.String value);
        partial void OnDimensionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HistoricPeriod
        {
            get
            {
                return _HistoricPeriod;
            }
            set
            {
                OnHistoricPeriodChanging(value);
                ReportPropertyChanging("HistoricPeriod");
                _HistoricPeriod = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HistoricPeriod");
                OnHistoricPeriodChanged();
            }
        }
        private global::System.String _HistoricPeriod;
        partial void OnHistoricPeriodChanging(global::System.String value);
        partial void OnHistoricPeriodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationIdFK
        {
            get
            {
                return _LocationIdFK;
            }
            set
            {
                OnLocationIdFKChanging(value);
                ReportPropertyChanging("LocationIdFK");
                _LocationIdFK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationIdFK");
                OnLocationIdFKChanged();
            }
        }
        private global::System.Int32 _LocationIdFK;
        partial void OnLocationIdFKChanging(global::System.Int32 value);
        partial void OnLocationIdFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderFormIdFK
        {
            get
            {
                return _OrderFormIdFK;
            }
            set
            {
                OnOrderFormIdFKChanging(value);
                ReportPropertyChanging("OrderFormIdFK");
                _OrderFormIdFK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderFormIdFK");
                OnOrderFormIdFKChanged();
            }
        }
        private global::System.Int32 _OrderFormIdFK;
        partial void OnOrderFormIdFKChanging(global::System.Int32 value);
        partial void OnOrderFormIdFKChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MuseumModel", "FK_tblExhibits_tblLocations", "tblLocations")]
        public tblLocation tblLocation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLocation>("MuseumModel.FK_tblExhibits_tblLocations", "tblLocations").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLocation>("MuseumModel.FK_tblExhibits_tblLocations", "tblLocations").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblLocation> tblLocationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLocation>("MuseumModel.FK_tblExhibits_tblLocations", "tblLocations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblLocation>("MuseumModel.FK_tblExhibits_tblLocations", "tblLocations", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MuseumModel", "FK_tblExhibits_tblOrderForms", "tblOrderForms")]
        public tblOrderForm tblOrderForm
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOrderForm>("MuseumModel.FK_tblExhibits_tblOrderForms", "tblOrderForms").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOrderForm>("MuseumModel.FK_tblExhibits_tblOrderForms", "tblOrderForms").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblOrderForm> tblOrderFormReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOrderForm>("MuseumModel.FK_tblExhibits_tblOrderForms", "tblOrderForms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblOrderForm>("MuseumModel.FK_tblExhibits_tblOrderForms", "tblOrderForms", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MuseumModel", Name="tblLocation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblLocation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblLocation object.
        /// </summary>
        /// <param name="locationId">Initial value of the LocationId property.</param>
        /// <param name="locationName">Initial value of the LocationName property.</param>
        public static tblLocation CreatetblLocation(global::System.Int32 locationId, global::System.String locationName)
        {
            tblLocation tblLocation = new tblLocation();
            tblLocation.LocationId = locationId;
            tblLocation.LocationName = locationName;
            return tblLocation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationId
        {
            get
            {
                return _LocationId;
            }
            set
            {
                if (_LocationId != value)
                {
                    OnLocationIdChanging(value);
                    ReportPropertyChanging("LocationId");
                    _LocationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocationId");
                    OnLocationIdChanged();
                }
            }
        }
        private global::System.Int32 _LocationId;
        partial void OnLocationIdChanging(global::System.Int32 value);
        partial void OnLocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LocationName
        {
            get
            {
                return _LocationName;
            }
            set
            {
                OnLocationNameChanging(value);
                ReportPropertyChanging("LocationName");
                _LocationName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LocationName");
                OnLocationNameChanged();
            }
        }
        private global::System.String _LocationName;
        partial void OnLocationNameChanging(global::System.String value);
        partial void OnLocationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surface_m2_
        {
            get
            {
                return _Surface_m2_;
            }
            set
            {
                OnSurface_m2_Changing(value);
                ReportPropertyChanging("Surface_m2_");
                _Surface_m2_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surface_m2_");
                OnSurface_m2_Changed();
            }
        }
        private global::System.String _Surface_m2_;
        partial void OnSurface_m2_Changing(global::System.String value);
        partial void OnSurface_m2_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LeasePrice
        {
            get
            {
                return _LeasePrice;
            }
            set
            {
                OnLeasePriceChanging(value);
                ReportPropertyChanging("LeasePrice");
                _LeasePrice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LeasePrice");
                OnLeasePriceChanged();
            }
        }
        private global::System.String _LeasePrice;
        partial void OnLeasePriceChanging(global::System.String value);
        partial void OnLeasePriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MuseumIdFK
        {
            get
            {
                return _MuseumIdFK;
            }
            set
            {
                OnMuseumIdFKChanging(value);
                ReportPropertyChanging("MuseumIdFK");
                _MuseumIdFK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MuseumIdFK");
                OnMuseumIdFKChanged();
            }
        }
        private Nullable<global::System.Int32> _MuseumIdFK;
        partial void OnMuseumIdFKChanging(Nullable<global::System.Int32> value);
        partial void OnMuseumIdFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MuseumModel", "FK_tblExhibits_tblLocations", "tblExhibits")]
        public EntityCollection<tblExhibit> tblExhibits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblExhibit>("MuseumModel.FK_tblExhibits_tblLocations", "tblExhibits");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblExhibit>("MuseumModel.FK_tblExhibits_tblLocations", "tblExhibits", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MuseumModel", "FK_tblLocations_tblMuseum", "tblMuseum")]
        public tblMuseum tblMuseum
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMuseum>("MuseumModel.FK_tblLocations_tblMuseum", "tblMuseum").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMuseum>("MuseumModel.FK_tblLocations_tblMuseum", "tblMuseum").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblMuseum> tblMuseumReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMuseum>("MuseumModel.FK_tblLocations_tblMuseum", "tblMuseum");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblMuseum>("MuseumModel.FK_tblLocations_tblMuseum", "tblMuseum", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MuseumModel", Name="tblMuseum")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMuseum : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMuseum object.
        /// </summary>
        /// <param name="museumId">Initial value of the MuseumId property.</param>
        /// <param name="museumName">Initial value of the MuseumName property.</param>
        public static tblMuseum CreatetblMuseum(global::System.Int32 museumId, global::System.String museumName)
        {
            tblMuseum tblMuseum = new tblMuseum();
            tblMuseum.MuseumId = museumId;
            tblMuseum.MuseumName = museumName;
            return tblMuseum;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MuseumId
        {
            get
            {
                return _MuseumId;
            }
            set
            {
                if (_MuseumId != value)
                {
                    OnMuseumIdChanging(value);
                    ReportPropertyChanging("MuseumId");
                    _MuseumId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MuseumId");
                    OnMuseumIdChanged();
                }
            }
        }
        private global::System.Int32 _MuseumId;
        partial void OnMuseumIdChanging(global::System.Int32 value);
        partial void OnMuseumIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MuseumName
        {
            get
            {
                return _MuseumName;
            }
            set
            {
                OnMuseumNameChanging(value);
                ReportPropertyChanging("MuseumName");
                _MuseumName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MuseumName");
                OnMuseumNameChanged();
            }
        }
        private global::System.String _MuseumName;
        partial void OnMuseumNameChanging(global::System.String value);
        partial void OnMuseumNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MuseumAddress
        {
            get
            {
                return _MuseumAddress;
            }
            set
            {
                OnMuseumAddressChanging(value);
                ReportPropertyChanging("MuseumAddress");
                _MuseumAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MuseumAddress");
                OnMuseumAddressChanged();
            }
        }
        private global::System.String _MuseumAddress;
        partial void OnMuseumAddressChanging(global::System.String value);
        partial void OnMuseumAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Established
        {
            get
            {
                return _Established;
            }
            set
            {
                OnEstablishedChanging(value);
                ReportPropertyChanging("Established");
                _Established = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Established");
                OnEstablishedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Established;
        partial void OnEstablishedChanging(Nullable<global::System.DateTime> value);
        partial void OnEstablishedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MuseumModel", "FK_tblLocations_tblMuseum", "tblLocations")]
        public EntityCollection<tblLocation> tblLocations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblLocation>("MuseumModel.FK_tblLocations_tblMuseum", "tblLocations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblLocation>("MuseumModel.FK_tblLocations_tblMuseum", "tblLocations", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MuseumModel", Name="tblOrderForm")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblOrderForm : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblOrderForm object.
        /// </summary>
        /// <param name="orderFormId">Initial value of the OrderFormId property.</param>
        /// <param name="buyerIdFk">Initial value of the BuyerIdFk property.</param>
        public static tblOrderForm CreatetblOrderForm(global::System.Int32 orderFormId, global::System.Int32 buyerIdFk)
        {
            tblOrderForm tblOrderForm = new tblOrderForm();
            tblOrderForm.OrderFormId = orderFormId;
            tblOrderForm.BuyerIdFk = buyerIdFk;
            return tblOrderForm;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderFormId
        {
            get
            {
                return _OrderFormId;
            }
            set
            {
                if (_OrderFormId != value)
                {
                    OnOrderFormIdChanging(value);
                    ReportPropertyChanging("OrderFormId");
                    _OrderFormId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderFormId");
                    OnOrderFormIdChanged();
                }
            }
        }
        private global::System.Int32 _OrderFormId;
        partial void OnOrderFormIdChanging(global::System.Int32 value);
        partial void OnOrderFormIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BuyerAdress
        {
            get
            {
                return _BuyerAdress;
            }
            set
            {
                OnBuyerAdressChanging(value);
                ReportPropertyChanging("BuyerAdress");
                _BuyerAdress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BuyerAdress");
                OnBuyerAdressChanged();
            }
        }
        private global::System.String _BuyerAdress;
        partial void OnBuyerAdressChanging(global::System.String value);
        partial void OnBuyerAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuyerIdFk
        {
            get
            {
                return _BuyerIdFk;
            }
            set
            {
                OnBuyerIdFkChanging(value);
                ReportPropertyChanging("BuyerIdFk");
                _BuyerIdFk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuyerIdFk");
                OnBuyerIdFkChanged();
            }
        }
        private global::System.Int32 _BuyerIdFk;
        partial void OnBuyerIdFkChanging(global::System.Int32 value);
        partial void OnBuyerIdFkChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MuseumModel", "FK_tblOrderForms_tblBuyers", "tblBuyers")]
        public tblBuyer tblBuyer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblBuyer>("MuseumModel.FK_tblOrderForms_tblBuyers", "tblBuyers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblBuyer>("MuseumModel.FK_tblOrderForms_tblBuyers", "tblBuyers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblBuyer> tblBuyerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblBuyer>("MuseumModel.FK_tblOrderForms_tblBuyers", "tblBuyers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblBuyer>("MuseumModel.FK_tblOrderForms_tblBuyers", "tblBuyers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MuseumModel", "FK_tblExhibits_tblOrderForms", "tblExhibits")]
        public EntityCollection<tblExhibit> tblExhibits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblExhibit>("MuseumModel.FK_tblExhibits_tblOrderForms", "tblExhibits");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblExhibit>("MuseumModel.FK_tblExhibits_tblOrderForms", "tblExhibits", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MuseumModel", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUser object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="isAdministrator">Initial value of the IsAdministrator property.</param>
        public static tblUser CreatetblUser(global::System.Int32 userId, global::System.String name, global::System.String userName, global::System.String password, global::System.Boolean isAdministrator)
        {
            tblUser tblUser = new tblUser();
            tblUser.UserId = userId;
            tblUser.Name = name;
            tblUser.UserName = userName;
            tblUser.Password = password;
            tblUser.IsAdministrator = isAdministrator;
            return tblUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdministrator
        {
            get
            {
                return _IsAdministrator;
            }
            set
            {
                OnIsAdministratorChanging(value);
                ReportPropertyChanging("IsAdministrator");
                _IsAdministrator = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdministrator");
                OnIsAdministratorChanged();
            }
        }
        private global::System.Boolean _IsAdministrator;
        partial void OnIsAdministratorChanging(global::System.Boolean value);
        partial void OnIsAdministratorChanged();

        #endregion

    
    }

    #endregion

    
}
